apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-app-sa
      imagePullSecrets:
      - name: jfrog-docker-secret
      containers:
      - name: my-app-container
        # Reference your JFrog-hosted Docker image here
        #image: trialwekr6h.jfrog.io/testing-docker/my-testing-image:latest
        image: nginx:latest
        ports:
        - containerPort: 8080
